### ISSUE TITLE
Delete not behaving properly

### ISSUE THREAD

**Issue by emaxedon** [vinctustech/energize#58]
When deleting a "todo" DELETE http://localhost:8080/todo/3

```

energize[ERROR] org.apache.http.ProtocolException: Invalid request line: {
energize[ERROR] 	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:209)
energize[ERROR] 	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:262)
energize[ERROR] 	at org.apache.http.impl.nio.DefaultHttpServerIODispatch.onInputReady(DefaultHttpServerIODispatch.java:215)
energize[ERROR] 	at org.apache.http.impl.nio.DefaultHttpServerIODispatch.onInputReady(DefaultHttpServerIODispatch.java:53)
energize[ERROR] 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
energize[ERROR] 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
energize[ERROR] 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
energize[ERROR] 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
energize[ERROR] 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
energize[ERROR] 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
energize[ERROR] 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
energize[ERROR] 	at java.lang.Thread.run(Thread.java:748)
energize[ERROR] Caused by: org.apache.http.ParseException: Invalid request line: {
energize[ERROR] 	at org.apache.http.message.BasicLineParser.parseRequestLine(BasicLineParser.java:291)
energize[ERROR] 	at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:117)
energize[ERROR] 	at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:50)
energize[ERROR] 	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
energize[ERROR] 	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:207)
energize[ERROR] 	... 11 more

```

**Comment by edadma** [comment]
can't reproduce using curl
