### ISSUE TITLE
Line break error when parsing .energize file when using Windows

### ISSUE THREAD

**Issue by DamnStraight** [vinctustech/energize#61]
On Windows, when the `.energize` file uses CRLF for line breaks, it causes the following error:

```
newfifthestate-com H2 JDBC Driver 1.4.197 (2018-03-18)
newfifthestate-com defining server..
 newfifthestate-com[ERROR] Exception in thread "main" java.lang.RuntimeException: 3: 'routes' expected but Newline found
newfifthestate-com[ERROR]
newfifthestate-com[ERROR]  
newfifthestate-com[ERROR]       at scala.sys.package$.error(package.scala:27)
newfifthestate-com[ERROR]       at xyz.hyperreal.funl2.package$.problem(funl2.scala:16)
newfifthestate-com[ERROR]       at xyz.hyperreal.funl2.FunLParser.parseFromString(FunLParser.scala:186)
newfifthestate-com[ERROR]       at xyz.hyperreal.funl2.FunLParser.parseFromSource(FunLParser.scala:181)
newfifthestate-com[ERROR]       at xyz.hyperreal.energize.Definition$.define(Definition.scala:51)
newfifthestate-com[ERROR]       at
xyz.hyperreal.energize.EnergizeServer$.instance(EnergizeServer.scala:36)
newfifthestate-com[ERROR]       at
xyz.hyperreal.energize.ServerMain$.delayedEndpoint$xyz$hyperreal$energize$ServerMain$1(ServerMain.scala:32)   newfifthestate-com[ERROR]
xyz.hyperreal.energize.ServerMain$delayedInit$body.apply(ServerMain.scala:6)
newfifthestate-com[ERROR]       at scala.Function0.apply$mcV$sp(Function0.scala:34)
newfifthestate-com[ERROR]       at scala.Function0.apply$mcV$sp$(Function0.scala:34) 
newfifthestate-com[ERROR]       at
scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
newfifthestate-com[ERROR]       at scala.App.$anonfun$main$1$adapted(App.scala:76)
newfifthestate-com[ERROR]       at scala.collection.immutable.List.foreach(List.scala:389)
newfifthestate-com[ERROR]       at scala.App.main(App.scala:76)
newfifthestate-com[ERROR]       at scala.App.main$(App.scala:74)
newfifthestate-com[ERROR]       at xyz.hyperreal.energize.ServerMain$.main(ServerMain.scala:6)
newfifthestate-com[ERROR]       at xyz.hyperreal.energize.ServerMain.main(ServerMain.scala)
newfifthestate-com ... finished with exit code 1 
 ```

When I change the line breaks for the `.energize` file to LF as oppose to CRLF, it doesn't produce this error.

**Comment by edadma** [comment]
it was never tested on Windows. i'm on it.

**Comment by edadma** [comment]
fixed
`git pull` on branch `master` to get the latest version (v0.12.5)
