### ISSUE TITLE
Error when using requestJSON with Eventbrite API

### ISSUE THREAD

**Issue by emaxedon** [vinctustech/energize#62]
When I make an api request to `api/events` with the following energize definition:

```
routes
	GET /api/events => Ok(res, requestJSON('https://www.eventbriteapi.com/v3/users/me/owned_events/?token=VT67SJBBZUG5IMVRMFTM'))
```

I get the following error:

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at xyz.hyperreal.json.JSONReader.$anonfun$string$1(JSONReader.scala:240)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
	at xyz.hyperreal.json.JSONReader.read$3(JSONReader.scala:231)
	at xyz.hyperreal.json.JSONReader.string(JSONReader.scala:269)
	at xyz.hyperreal.json.JSONReader.value(JSONReader.scala:162)
	at xyz.hyperreal.json.JSONReader.pair(JSONReader.scala:134)
	at xyz.hyperreal.json.JSONReader.members(JSONReader.scala:117)
	at xyz.hyperreal.json.JSONReader.dictionary(JSONReader.scala:112)
	at xyz.hyperreal.json.JSONReader.value(JSONReader.scala:161)
	at xyz.hyperreal.json.JSONReader.pair(JSONReader.scala:134)
	at xyz.hyperreal.json.JSONReader.members(JSONReader.scala:117)
	at xyz.hyperreal.json.JSONReader.members(JSONReader.scala:121)
	at xyz.hyperreal.json.JSONReader.dictionary(JSONReader.scala:112)
	at xyz.hyperreal.json.JSONReader.value(JSONReader.scala:161)
	at xyz.hyperreal.json.JSONReader.elements(JSONReader.scala:146)
	at xyz.hyperreal.json.JSONReader.array(JSONReader.scala:143)
	at xyz.hyperreal.json.JSONReader.value(JSONReader.scala:160)
	at xyz.hyperreal.json.JSONReader.pair(JSONReader.scala:134)
	at xyz.hyperreal.json.JSONReader.members(JSONReader.scala:117)
	at xyz.hyperreal.json.JSONReader.members(JSONReader.scala:121)
	at xyz.hyperreal.json.JSONReader.dictionary(JSONReader.scala:112)
	at xyz.hyperreal.json.JSONReader.fromReader(JSONReader.scala:79)
	at xyz.hyperreal.json.JSONReader.fromString(JSONReader.scala:76)
	at xyz.hyperreal.json.DefaultJSONReader$.fromString(JSONReader.scala:23)
	at xyz.hyperreal.energize.ClientFunctions$.requestJSON(ClientFunctions.scala:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at xyz.hyperreal.bvm.Native$$anon$1.apply(Native.scala:28)
	at xyz.hyperreal.bvm.VM.callIndirect(VM.scala:392)
	at xyz.hyperreal.bvm.VM.run(VM.scala:500)
	at xyz.hyperreal.bvm.VM.call(VM.scala:1079)
	at xyz.hyperreal.energize.Processor.liftedTree1$1(Processor.scala:202)
	at xyz.hyperreal.energize.Processor.process(Processor.scala:201)
	at xyz.hyperreal.energize.EnergizeServer$RequestHandler.handleInternal(EnergizeServer.scala:142)
	at xyz.hyperreal.energize.EnergizeServer$RequestHandler.handle(EnergizeServer.scala:98)
	at xyz.hyperreal.energize.EnergizeServer$RequestHandler.handle(EnergizeServer.scala:84)
	at org.apache.http.nio.protocol.HttpAsyncService.responseReady(HttpAsyncService.java:454)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.produceOutput(DefaultNHttpServerConnection.java:307)
	at org.apache.http.impl.nio.DefaultHttpServerIODispatch.onOutputReady(DefaultHttpServerIODispatch.java:220)
	at org.apache.http.impl.nio.DefaultHttpServerIODispatch.onOutputReady(DefaultHttpServerIODispatch.java:53)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:145)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:188)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:341)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by emaxedon** [comment]
Under the `ClientFunctions` object at src/main/scala/ClientFunctions.scala`, I tried setting headers to ensure the Eventbrite API is returning parse-able JSON, didn't quite work though...

```
object ClientFunctions {

  def requestJSON( vm: VM, url: String ): Any =
    DefaultJSONReader.fromString(
      Request.Get(url)
      	.addHeader("Accept", "application/json")
      	.addHeader("Content-type", "text/json")
        .connectTimeout(1000)
        .socketTimeout(1000)
        .execute.returnContent.asString )

}
```

I'll investigate more.

**Comment by emaxedon** [comment]
Here's the exact payload that is passed to the `DefaultJSONReader.fromString(payload)`.

```
{"pagination": {"object_count": 11, "page_number": 1, "page_size": 50, "page_count": 1, "has_more_items": false}, "events": [{"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726230413", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726230413", "start": {"timezone": "America/Los_Angeles", "local": "2018-06-04T11:30:00", "utc": "2018-06-04T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-06-04T14:00:00", "utc": "2018-06-04T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726230413/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726231416", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726231416", "start": {"timezone": "America/Los_Angeles", "local": "2018-06-11T11:30:00", "utc": "2018-06-11T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-06-11T14:00:00", "utc": "2018-06-11T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726231416/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726232419", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726232419", "start": {"timezone": "America/Los_Angeles", "local": "2018-06-18T11:30:00", "utc": "2018-06-18T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-06-18T14:00:00", "utc": "2018-06-18T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726232419/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726233422", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726233422", "start": {"timezone": "America/Los_Angeles", "local": "2018-06-25T11:30:00", "utc": "2018-06-25T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-06-25T14:00:00", "utc": "2018-06-25T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726233422/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726234425", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726234425", "start": {"timezone": "America/Los_Angeles", "local": "2018-07-02T11:30:00", "utc": "2018-07-02T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-07-02T14:00:00", "utc": "2018-07-02T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726234425/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726235428", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726235428", "start": {"timezone": "America/Los_Angeles", "local": "2018-07-09T11:30:00", "utc": "2018-07-09T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-07-09T14:00:00", "utc": "2018-07-09T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726235428/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726236431", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726236431", "start": {"timezone": "America/Los_Angeles", "local": "2018-07-16T11:30:00", "utc": "2018-07-16T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-07-16T14:00:00", "utc": "2018-07-16T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726236431/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726237434", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726237434", "start": {"timezone": "America/Los_Angeles", "local": "2018-07-23T11:30:00", "utc": "2018-07-23T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-07-23T14:00:00", "utc": "2018-07-23T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726237434/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726238437", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726238437", "start": {"timezone": "America/Los_Angeles", "local": "2018-07-30T11:30:00", "utc": "2018-07-30T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-07-30T14:00:00", "utc": "2018-07-30T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726238437/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726239440", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726239440", "start": {"timezone": "America/Los_Angeles", "local": "2018-08-06T11:30:00", "utc": "2018-08-06T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-08-06T14:00:00", "utc": "2018-08-06T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726239440/", "series_id": "46726184275", "logo": null}, {"name": {"text": "Coffee Break Cool Down w/Kari", "html": "Coffee Break Cool Down w/Kari"}, "description": {"text": "Venice\u00a0Onsite Yoga Studio\nTeam \u2013 First Come First Serve \u2013 Sign Up \n", "html": "<P><SPAN>Venice\u00a0<\/SPAN>Onsite Yoga Studio<\/P>\n<P><SPAN>Team \u2013 First Come First Serve \u2013 Sign Up <\/SPAN><\/P>\n<P><SPAN><BR><\/SPAN><\/P>"}, "id": "46726240443", "url": "https://www.eventbrite.com/e/coffee-break-cool-down-wkari-tickets-46726240443", "start": {"timezone": "America/Los_Angeles", "local": "2018-08-13T11:30:00", "utc": "2018-08-13T18:30:00Z"}, "end": {"timezone": "America/Los_Angeles", "local": "2018-08-13T14:00:00", "utc": "2018-08-13T21:00:00Z"}, "organization_id": "150265288201", "created": "2018-06-04T17:41:02Z", "changed": "2018-06-04T21:52:30Z", "capacity": 45, "capacity_is_custom": false, "status": "draft", "currency": "USD", "listed": true, "shareable": true, "invite_only": false, "online_event": false, "show_remaining": false, "tx_time_limit": 480, "hide_start_date": false, "hide_end_date": false, "locale": "en_US", "is_locked": false, "privacy_setting": "unlocked", "is_series": true, "is_series_parent": false, "is_reserved_seating": false, "show_pick_a_seat": false, "show_seatmap_thumbnail": false, "show_colors_in_seatmap_thumbnail": false, "source": "create_2.0", "is_free": true, "version": "3.0.0", "logo_id": null, "organizer_id": "17415676298", "venue_id": "25120113", "category_id": "107", "subcategory_id": "7001", "format_id": "9", "resource_uri": "https://www.eventbriteapi.com/v3/events/46726240443/", "series_id": "46726184275", "logo": null}]}
```
